name: DawnEngine
version: 1.0
author: Pedrokase
main: io.github.pedrokase.DawnEngine

commands:
  roll:
    description: Allows the user to roll a d{X} {Y} times
    usage: /roll {dice_sides} {dice_number}